name: "Search pull-request comments"
description: "Verifies if a given user has left a comment on the pull-request"

branding:
  icon: "truck"
  color: "purple"

runs:
  using: "docker"
  image: "Dockerfile"